services:
  - type: web
    name: mega-video-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn bot:app"
    envVars:
      - key: BOT_TOKEN
        sync: false
